import React from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Link from 'next/link'

export default function Thankyou() {
    return (
        <div className={styles.container}>
          <Head>
            <title>Next.js + Airtable</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
    
          <main className={styles.main}>
            <h1>Airtable form confirmation page</h1>
            <p>This is Next.js and Airtable contest registration form template.</p>
            <Link href="/">Get back to home page</Link>
          </main>
    
          <footer className={styles.footer}>
    
          </footer>
        </div>
      )
}
